- src: geerlingguy.docker
  version: '7.3.0'
- src: griggheo.consul-template
- src: ahuffman.resolv
- src: darkwizard242.cni
- name: ansible-consul
  src: https://github.com/ansible-community/ansible-consul.git
  scm: git
  version: d5d5a02
- name: ansible-vault
  src: https://github.com/ansible-community/ansible-vault.git
  version: 09d9789
- name: ansible-nomad
  src: https://github.com/ansible-community/ansible-nomad.git
  scm: git
  version: a0f567e
- name: githubixx.cfssl
  src: https://github.com/githubixx/ansible-role-cfssl.git
  scm: git
  version: 8.3.0+1.6.5
- name: githubixx.consul-ca
  src: https://github.com/githubixx/ansible-role-consul-ca.git
  scm: git
  version: 2.0.0+1.0.2
